version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s: %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/main.log
    backupCount: 2
loggers:
  mainLogger:
    level: DEBUG
    handlers: [file]
    propagate: no
