from enum import Enum

class RuleEnum(Enum):
  IC_VS_GENDER = 1  # `ICNUMBER` vs `GENDER`
  LESION_VS_REFER_SPECIALIST = 2  # `LESION` vs `REFERAL TO SPECIALIST`
  IC_VS_DATEBIRTH = 3  # `DATEBIRTH` vs `ICNUMBER`
  DATESCREEN_VS_DATEREFER = 4 # `DATESCREEN` vs `DATE REFERRED` vs `DATE REFERRED QUIT SER`
  DATEREFER_VS_DATE_SEEN_SPECIALIST = 5 # `DATE REFERRED` vs `DATE SEEN BY SPECIALIST`
  DATEREFER_QUIT_VS_QUIT_APPT = 6 # `DATE REFERRED QUIT SER` vs `TARIKH TEMUJANJI QUIT SERVICE`
