from enum import Enum

class RuleEnum(Enum):
  IC_VS_GENDER = 1  # `ICNUMBER` vs `GENDER`
  LESION_VS_REFER_SPECIALIST = 2  # `LESION` vs `REFERAL TO SPECIALIST`
  IC_VS_DATEBIRTH = 3  # `DATEBIRTH` vs `ICNUMBER`
